name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'typescript/**'

jobs:
  typescript-tests:
    name: Run TypeScript Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: changes
        uses: jitterbit/get-changed-files@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd typescript
          npm install

      - name: Run TypeScript Tests
        run: |
          cd typescript
          npm test